<?php

namespace Aescarcha\BusinessBundle\Repository;

/**
 * BusinessAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessAssetRepository extends \Doctrine\ORM\EntityRepository
{
}
