<?php

namespace Aescarcha\BusinessBundle\Repository;

use Aescarcha\BusinessBundle\Entity\Business;

/**
 * BusinessAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessAssetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByBusiness( Business $business, $returnQuery = true )
    {
        $qb = $this->createQueryBuilder('p');
                $qb->where($qb->expr()->eq('p.business', ':p_business'))
                ->setParameter('p_business', $business);
        return $returnQuery ? $qb : $qb->getQuery()->getResult();
    }
}
